sonar.projectKey=kartikey-dev_portfolio
sonar.projectName=Kumar Kartikey Portfolio
sonar.organization=kartikey-dev

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/__mocks__/**

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
